%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/galactic/.*$
%global __requires_exclude_from ^/opt/ros/galactic/.*$

Name:           ros-galactic-cyclonedds
Version:        0.8.0
Release:        6%{?dist}%{?release_suffix}
Summary:        ROS cyclonedds package

License:        Eclipse Public License 2.0
URL:            https://projects.eclipse.org/projects/iot.cyclonedds
Source0:        %{name}-%{version}.tar.gz

Requires:       openssl
Requires:       ros-galactic-iceoryx-binding-c
Requires:       ros-galactic-iceoryx-posh
Requires:       ros-galactic-iceoryx-utils
Requires:       ros-galactic-ros-workspace
BuildRequires:  CUnit-devel
BuildRequires:  bison
BuildRequires:  cmake3
BuildRequires:  openssl-devel
BuildRequires:  ros-galactic-iceoryx-binding-c
BuildRequires:  ros-galactic-iceoryx-posh
BuildRequires:  ros-galactic-iceoryx-utils
BuildRequires:  ros-galactic-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Eclipse Cyclone DDS is a very performant and robust open-source DDS
implementation. Cyclone DDS is developed completely in the open as an Eclipse
IoT project.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/galactic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/galactic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/galactic

%changelog
* Fri Dec 17 2021 Eclipse Foundation, Inc. <cyclonedds-dev@eclipse.org> - 0.8.0-6
- Autogenerated by Bloom

* Mon Jun 07 2021 Eclipse Foundation, Inc. <cyclonedds-dev@eclipse.org> - 0.8.0-5
- Autogenerated by Bloom

* Tue Apr 20 2021 Eclipse Foundation, Inc. <cyclonedds-dev@eclipse.org> - 0.8.0-4
- Autogenerated by Bloom

* Tue Apr 13 2021 Eclipse Foundation, Inc. <cyclonedds-dev@eclipse.org> - 0.8.0-3
- Autogenerated by Bloom

* Thu Apr 08 2021 Eclipse Foundation, Inc. <cyclonedds-dev@eclipse.org> - 0.8.0-2
- Autogenerated by Bloom

* Mon Apr 05 2021 Eclipse Foundation, Inc. <cyclonedds-dev@eclipse.org> - 0.8.0-1
- Autogenerated by Bloom

* Mon Mar 08 2021 Eclipse Foundation, Inc. <cyclonedds-dev@eclipse.org> - 0.7.0-1
- Autogenerated by Bloom

